spring:
  application:
    name: learning-app
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/learning_app?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Root@123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:S+93O14n+zAHUqsPg8ZAlzG4VoIUnKANGN28TvSs6XgoDEU15/g1qmGaBIv6jMTfiyi3aXltkXnM62jJtDN/NA==}
  expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}

admin:
  email: ${ADMIN_EMAIL:admin@example.com}
  password: ${ADMIN_PASSWORD:Dangthuc02@}
  display-name: ${ADMIN_DISPLAY_NAME:Admin}

springdoc:
  swagger-ui:
    path: /docs
